### ISSUE TITLE
Chat line overflows

### ISSUE THREAD

**Issue by NabilaAhmedAdity** [forthright48/chat-app#1]
Text has to fit in one line. No extra line for large text.

**Comment by forthright48** [comment]
So basically, the chat lines are trying to fit into one line. Long lines overflow and can't be seen in screen. 

Need to wrap the lines into new lines.

**Comment by forthright48** [comment]
So here is the details of the problem:

If you write a long sentence, eg: "1 2 3 4 5 .... 1000", then it will wrap in multiple line. So it works properly with long sentences. 

The problem lies in when we input long "word", for example "1234567891011...100". Notice there is no space. In this case, the default behavior is to fit the whole thing in one line.

Fixing the issue was easy, since I am using CSS3. I simply attached this:

```
#messages li {
  word-wrap: break-word;
}
```
